1.0.6 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -87,7 +87,10 @@ usage()
 
       --unpack-tarball T     acquire .debs from a tarball instead of http
       --make-tarball T       download .debs and create a tarball (tgz format)
-
+      --second-stage-target DIR
+                             Run second stage in a subdirectory instead of root
+                               (can be used to create a foreign chroot)
+                               (requires --second-stage)
       --boot-floppies        used for internal purposes by boot-floppies
       --debian-installer     used for internal purposes by debian-installer
 EOF
@@ -142,6 +145,18 @@ if [ $# != 0 ] ; then
         SECOND_STAGE_ONLY=true
 	shift
 	;;
+    --second-stage-target)
+       if [ "$SECOND_STAGE_ONLY" = "true" ] ; then
+          if [ -n "$2" ] ; then
+            CHROOTDIR="$2"
+            shift 2
+          else
+            error 1 NEEDARG "option requires an argument: %s" "$1"
+          fi
+        else
+            error 1 NEEDARG "%s only applies in the second stage" "$1"
+        fi
+      ;;
       --print-debs)
         WHAT_TO_DO="finddebs printdebs kill_target"
         shift
@@ -242,10 +257,14 @@ if [ "$SECOND_STAGE_ONLY" = "true" ]; then
     VARIANT=$(cat $DEBOOTSTRAP_DIR/variant)
     SUPPORTED_VARIANTS="$VARIANT"
   fi
-  TARGET=/
+  if [ "$CHROOTDIR" = "" ]; then
+    TARGET=/
+  else
+    TARGET=$CHROOTDIR
+  fi
   SCRIPT=$DEBOOTSTRAP_DIR/suite-script
 else
-  if [ "$1" = "" -o "$2" = "" ]; then
+  if [ "$1" = "" ] || [ "$2" = "" ]; then
     usage_err 1 NEEDSUITETARGET "You must specify a suite and a target."
   fi
   SUITE="$1"
@@ -260,7 +279,7 @@ else
   fi
 
   SCRIPT="$DEBOOTSTRAP_DIR/scripts/$1"
-  if [ -n "$VARIANT" -a -e "${SCRIPT}.${VARIANT}" ]; then
+  if [ -n "$VARIANT" ] && [ -e "${SCRIPT}.${VARIANT}" ]; then
     SCRIPT="${SCRIPT}.${VARIANT}"
     SUPPORTED_VARIANTS="$VARIANT"
   fi
@@ -287,6 +306,10 @@ export ARCH SUITE TARGET
 if am_doing_phase first_stage second_stage; then
   if [ -x /usr/bin/id ] && [ `id -u` -ne 0 ]; then
     error 1 NEEDROOT "debootstrap can only run as root"
+  fi
+  # Ensure that we can create working devices and executables on the target.
+  if ! check_sane_mount "$TARGET"; then
+    error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
   fi
 fi
 
@@ -372,7 +395,7 @@ fi
 ###########################################################################
 
 if am_doing_phase finddebs; then
-  if [ "$FINDDEBS_NEEDS_INDICES" = "true" -o "$RESOLVE_DEPS" = "true" ]; then
+  if [ "$FINDDEBS_NEEDS_INDICES" = "true" ] || [ "$RESOLVE_DEPS" = "true" ]; then
     download_indices
     GOT_INDICES=true
   fi
