0.2.45ubuntu27 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -18,6 +18,7 @@ GETTEXT_LANG=$LANG
 LANG=C
 USE_COMPONENTS=main
 VARIANT=""
+KEYRING=""
 DEBCONF_ADMIN_EMAIL=""
 
 export LANG USE_COMPONENTS DEBCONF_ADMIN_EMAIL
@@ -51,6 +52,7 @@ usage()
                              archive
       --variant=X            use variant X of the bootstrap scripts
                              (currently supported variants: buildd)
+      --keyring=K            check Release files against keyring K
 EOF
 }
 
@@ -130,6 +132,13 @@ if [ $# != 0 ] ; then
     VARIANT="$(echo "$1" | cut -f2 -d"=")"
     shift 1
     ;;
+  --keyring*)
+    if ! gpgv --version >/dev/null 2>&1; then
+        error 1 NEEDGPGV "gpgv not installed, but required by --keyring option"
+    fi
+    KEYRING="$(echo "$1" | cut -f2 -d"=")"
+    shift 1
+    ;;
 	*)
 	  break
 	  ;;
@@ -139,7 +148,7 @@ else
   usage_err 1 NEEDSUITETARGET "You must specify a suite and a target."
 fi
 
-if [ "$1" = "" -o \( "$2" = "" -a "$JUST_PRINT_DEBS" = "" \) ]; then
+if [ "$1" = "" ] || ( [ "$2" = "" ] && [ "$JUST_PRINT_DEBS" = "" ] ); then
   usage_err 1 NEEDSUITETARGET "You must specify a suite and a target."
 fi
 
@@ -182,7 +191,7 @@ fi
 
 export MIRRORS ARCH SUITE TARGET
 
-if [ "$JUST_PRINT_DEBS" = "" -a "$DOWNLOAD_ONLY" = "" -a -x /usr/bin/id ] && [ `id -u` -ne 0 ]; then
+if [ "$JUST_PRINT_DEBS" = "" ] && [ "$DOWNLOAD_ONLY" = "" ] && [ -x /usr/bin/id ] && [ `id -u` -ne 0 ]; then
   error 1 NEEDROOT "debootstrap can only run as root"
 fi
 
