1.0.36 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -29,6 +29,7 @@ DISABLE_KEYRING=""
 VARIANT=""
 ARCH=""
 HOST_ARCH=""
+HOST_OS=""
 KEEP_DEBOOTSTRAP_DIR=""
 USE_DEBIANINSTALLER_INTERACTION=""
 SECOND_STAGE_ONLY=""
@@ -78,7 +79,7 @@ usage_err()
 usage()
 {
 	echo "Usage: ${0##*/} [OPTION]... <suite> <target> [<mirror> [<script>]]"
-	echo "Bootstrap Debian base system."
+	echo "Bootstrap a Debian base system into a target directory."
 	echo
 	cat <<EOF
       --help                 display this help and exit
@@ -88,7 +89,7 @@ usage()
       --download-only        download packages, but don't perform installation
       --print-debs           print the packages to be installed, and exit
 
-      --arch=A               set the target architecture (use if no dpkg)
+      --arch=A               set the architecture to install (use if no dpkg)
                                [ --arch=powerpc ]
 
       --include=A,B,C        adds specified names to the list of base packages
@@ -390,20 +391,47 @@ fi
 
 ###########################################################################
 
-if [ -x /usr/bin/dpkg ] && \
-     /usr/bin/dpkg --print-architecture >/dev/null 2>&1; then
+if in_path dpkg && \
+     dpkg --print-architecture >/dev/null 2>&1; then
 	HOST_ARCH=`/usr/bin/dpkg --print-architecture`
-elif type udpkg >/dev/null 2>&1 && \
+elif in_path udpkg && \
      udpkg --print-architecture >/dev/null 2>&1; then
 	HOST_ARCH=`/usr/bin/udpkg --print-architecture`
 elif [ -e $DEBOOTSTRAP_DIR/arch ]; then
 	HOST_ARCH=`cat $DEBOOTSTRAP_DIR/arch`
-else
-	error 1 WHATARCH "Couldn't work out current architecture"
+fi
+HOST_OS="$HOST_ARCH"
+# basic host OS guessing for non-Debian systems
+if [ -z "$HOST_OS" ]; then
+	case `uname` in
+		Linux)
+			HOST_OS=linux
+		;;
+		GNU/kFreeBSD)
+			HOST_OS=kfreebsd
+		;;
+		GNU)
+			HOST_OS=hurd
+		;;
+		FreeBSD*)
+			HOST_OS=freebsd
+		;;
+	esac
 fi
 
 if [ -z "$ARCH" ]; then
 	ARCH=$HOST_ARCH
+fi
+
+if [ -z "$ARCH" ] || [ -z "$HOST_OS" ]; then
+        error 1 WHATARCH "Couldn't work out current architecture"
+
+fi
+
+if [ "$HOST_OS" = "kfreebsd" ] || [ "$HOST_OS" = "freebsd" ]; then
+	for module in "linprocfs fdescfs tmpfs linsysfs"; do
+		kldstat -m "$module" > /dev/null 2>&1 || warning SANITYCHECK "Probably required module %s is not loaded" "$module"
+	done
 fi
 
 if [ "$TARGET" = "/" ]; then
@@ -425,8 +453,7 @@ fi
 if [ -z "$SHA_SIZE" ]; then
 	SHA_SIZE=256
 fi
-if ! [ -x "/usr/bin/sha${SHA_SIZE}sum" ] && \
-   ! [ -x "/bin/sha${SHA_SIZE}sum" ]; then
+if ! in_path "sha${SHA_SIZE}sum" && ! in_path "sha${SHA_SIZE}"; then
 	SHA_SIZE=1
 fi
 DEBOOTSTRAP_CHECKSUM_FIELD="SHA$SHA_SIZE"
@@ -434,7 +461,7 @@ DEBOOTSTRAP_CHECKSUM_FIELD="SHA$SHA_SIZE"
 export ARCH SUITE TARGET CHROOT_CMD SHA_SIZE DEBOOTSTRAP_CHECKSUM_FIELD
 
 if am_doing_phase first_stage second_stage; then
-	if [ -x /usr/bin/id ] && [ `id -u` -ne 0 ]; then
+	if in_path id && [ `id -u` -ne 0 ]; then
 		error 1 NEEDROOT "debootstrap can only run as root"
 	fi
 	# Ensure that we can create working devices and executables on the target.
